--Tao user nhan vien
CREATE OR REPLACE PROCEDURE USP_CREATEUSER
AS
    CURSOR CUR IS (SELECT MANV
        FROM ADMIN.TB_NHANSU
        WHERE MANV NOT IN (SELECT USERNAME FROM ALL_USERS) );
    STRSQL VARCHAR(2000);
    USR VARCHAR2(5);
BEGIN
    OPEN CUR;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
    
        STRSQL := 'CREATE USER '||USR||' IDENTIFIED BY '||USR;
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT TO '||USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE(STRSQL);
    CLOSE CUR;
END;
/

--them user vao role
CREATE OR REPLACE PROCEDURE USP_ADDUSRMEM
    (STRROLE VARCHAR, VTRO VARCHAR)
AS
    CURSOR CUR IS (SELECT MANV
        FROM ADMIN.TB_NHANSU
        WHERE MANV IN (SELECT USERNAME FROM ALL_USERS)
        AND VAITRO = VTRO);
    STRSQL VARCHAR(2000);
    USR VARCHAR2(5);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
        
        STRSQL := 'GRANT '||STRROLE||' TO '||USR;
        EXECUTE IMMEDIATE (STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
--Tao user sinhvien
CREATE OR REPLACE PROCEDURE USP_CREATEUSER2
AS
    CURSOR CUR IS (SELECT MASV
        FROM ADMIN.TB_SINHVIEN
        WHERE MASV NOT IN (SELECT USERNAME FROM ALL_USERS) );
    STRSQL VARCHAR(2000);
    USR VARCHAR2(10);
BEGIN
    OPEN CUR;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE';
    EXECUTE IMMEDIATE(STRSQL);
    LOOP
        FETCH CUR INTO USR;
        EXIT WHEN CUR%NOTFOUND;
    
        STRSQL := 'CREATE USER '||USR||' IDENTIFIED BY '||USR;
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT TO '||USR;
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    STRSQL := 'ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE';
    EXECUTE IMMEDIATE(STRSQL);
    CLOSE CUR;
END;
/
--Tao user
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
EXEC USP_CREATEUSER;
EXEC USP_CREATEUSER2;
ALTER SESSION SET "_ORACLE_SCRIPT" = FALSE;