CREATE OR REPLACE PROCEDURE find_role(user_name IN VARCHAR2)
AUTHID CURRENT_USER
AS
    v_role VARCHAR2(50);
BEGIN 
    SELECT 'Sinh vien' INTO v_role FROM ADMIN.TB_SINHVIEN WHERE MASV = user_name;
EXCEPTION
    WHEN No_Data_Found THEN
        SELECT VAITRO INTO v_role FROM ADMIN.TB_NHANSU WHERE MANV = user_name;
    IF v_role IS NULL THEN
        SELECT 'He thong' INTO v_role FROM dba_users WHERE username = user_name;
    END IF;
    IF v_role IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('Vai trò c?a ng??i dùng');
    ELSE
        DBMS_OUTPUT.PUT_LINE(v_role);
    END IF;
END;
/
SET SERVEROUTPUT ON;
CALL FIND_ROLE('SV126109');
CALL FIND_ROLE('NV100');
CALL FIND_ROLE('sys');

--Proc lay ten user la sinh vien
CREATE OR REPLACE PROCEDURE admin.find_name(user_id IN VARCHAR2)
AS
BEGIN
  EXECUTE IMMEDIATE 'SELECT HOTEN FROM ADMIN.TB_SINHVIEN WHERE MASV = ''' || user_id || '''';
END;
/
CONN SV120221/SV120221;
SELECT HOTEN FROM ADMIN.TB_SINHVIEN WHERE MASV = 'SV120221';

